### PR TITLE
dragonos_gr-3.8

### PR DESCRIPTION
**Pull request by alphafox02**
Tested on a current installation of DragonOS Focal with GNU Radio 3.8 and the OOT GR-Soapy installed. Make sure to first open up and save the /grc/JAERO_USB_demod_heir.grc in GRC after installing gr-JAERO.

This will ensure the block is available when opening up the provided flow graphs.

### CODE REVIEW

**Comment by muaddib1984** [comment]
Let me check this out later, I can go ahead and make a maint-3.8 branch and change main to 3.10
I'll also throw a maint-3.9 on there for good measure.  Will get your changes merged over the next day or so.

**Comment by muaddib1984** [comment]
merged into maint-3.8
Could you do me a favor and clone the maint-3.8 branch and make sure it builds and runs ok?
I don't have a 3.8 install to test and had some issues merging on my end. Should be worked out now, but just wanted to make sure.

**Comment by alphafox02** [comment]
Sure thing! I’ll build it into my pi build tonight and see how it goes.

**Comment by alphafox02** [comment]
Built and installed without issue on my Pi with 3.8.1. Opened up the heir block, saved it and then open up example flow graphs without error. I also put it into DragonOS Focal. If you ever want to try it you can burn the iso to usb and run it all live without ever having to install. I put the source in /usr/src.

**Comment by muaddib1984** [comment]
Thanks for including it, Very exciting. 

Is the actual source code for DragonOS available or is it just the ISO on sourceforge?

**Comment by alphafox02** [comment]
Essentially the source code is one master machine I sit and work on, not the most efficient way of doing things I suppose. And when I say sit and work on, I mean I pull down and build everything myself before making a Live ISO. So you'll see that most all of the packages that are installed outside of the default repo is sitting in the /usr/src directory. I tried to leave everything I did behind in case someone needs to change something. On source force is basically a copy of that mater machine.

**Comment by muaddib1984** [comment]
That makes sense. I get what your doing. Sounds like something that could be distributed a little easier via docker. Im aware that for those unfamiliar it might be a bit intimidating but the build itself could be fairly simplistic. Lots of folks build on a host machine and for deployment just copy the bin and lib directories along with any necessary configs into the container when they build. Happy to discuss further off git. My email is in the commit logs for gr-JAERO.

**Pull request merged**
